### PR TITLE
[Bug fix] Ignoring ssl integrity check for assets files

### PR DESCRIPTION
**Pull request by MuriloChianfa**
Hey @Baspa 👋 long time no see you, im upgrading some package versions in my project and when i've tested the new versions of laravel-seo-scanner im receiving this error:

image

After these changes:

image

This PR aims to solve this problem, can u check if its relevant for the package?

### CODE REVIEW

**Comment by Baspa** [comment]
Hey @MuriloChianfa thank you for your PR! I will check this later today :)

**Comment by Baspa** [comment]
Are you using a local environment when running these checks? Did you check the paragraph "Running the scanner in a local environment"? 

You can already set the verification of SSL certificate to `false`. Or does that not fix you problem? @MuriloChianfa

**Comment by MuriloChianfa** [comment]
i've already setted the verification of SSL certificate to false, but seems thats missing on this step of the code, so we need to use these options to ignore the SSL certificates integrity

**Review by Baspa — COMMENTED** [review]
Can you set the verify to `false` only when the verify in the config is also set to false? Then I can merge it @MuriloChianfa

**Comment by Baspa** [comment]
Awesome, thanks! @MuriloChianfa

**Review by Baspa — APPROVED** [review]

**Pull request merged**
