### PR TITLE
Add Laravel 11 support

### PR DESCRIPTION
**Pull request by atmonshi**
also I ran the tests all green (3 skipped, 68 passed) :)

### CODE REVIEW

**Comment by Baspa** [comment]
Thanks for your PR! We should probably add separate tests for L11 or change the current workflows because I believe they're written to test Laravel 10 specifically. The tests were running fine locally I assume? @atmonshi

**Comment by atmonshi** [comment]
yes as mentioned :)
> also I ran the tests all green (3 skipped, 68 passed) :)

I updated the github action
and some of the dev dependencies
now its support laravel 9,10,11

the plugin: [pest-plugin-parallel](https://github.com/pestphp/pest-plugin-parallel) is now deprecated for pest 2
so not sure how to run it on l9!?

**Comment by Baspa** [comment]
> yes as mentioned :)
> 
> > also I ran the tests all green (3 skipped, 68 passed) :)
> 
> I updated the github action and some of the dev dependencies now its support laravel 9,10,11
> 
> the plugin: [pest-plugin-parallel](https://github.com/pestphp/pest-plugin-parallel) is now deprecated for pest 2 so not sure how to run it on l9!?

Seems like the Github actions need a PHP upgrade as well. The actions are still failing.

**Comment by atmonshi** [comment]
php 8,2 already there not sure why it falling
I added the php to `include` section let see...

**Comment by atmonshi** [comment]
for some reasons my [commits](https://github.com/vormkracht10/laravel-seo-scanner/compare/main...atmonshi:laravel-seo-scanner:laravel-11) not showing in this PR :)

**Comment by Baspa** [comment]
> for some reasons my [commits](https://github.com/vormkracht10/laravel-seo-scanner/compare/main...atmonshi:laravel-seo-scanner:laravel-11) not showing in this PR :)

Hmm weird, maybe that's because @markvaneijk made some changes but did not pull yours?

**Comment by atmonshi** [comment]
Screenshot 2024-03-01 at 6 26 41 PM

and I see this now when I click on his commit:
"This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository."


but I managed to pull his changes locally and push
but all my commits after that not showing here
github is confusing and acting out sometimes :)

**Comment by markvaneijk** [comment]
GitHub acts weird with files in `.github`, because I only changed code inside this PR, trying to fix the php version mismatch

**Comment by atmonshi** [comment]
Github feels a bit protective about `.github` 😂

I see all the tests are passing finally, thank you all

**Comment by markvaneijk** [comment]
Unfortunately it doesn't want to run the actions with the tests in it:

CleanShot 2024-03-01 at 17 17 17@2x

**Comment by atmonshi** [comment]
ah spoke too soon..
testing: remove the php from include.
let see if it fails normally!

**Comment by atmonshi** [comment]
finally got it all green [here](https://github.com/atmonshi/laravel-seo-scanner/pull/2)

**Comment by Baspa** [comment]
Checks looking good now here as well. @atmonshi

**Review by Baspa — APPROVED** [review]

**Pull request merged**
